on: [push]

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: matte-snyk/regula-action@master
      with:
        input_path: infra_tf
        rego_paths: example_custom_rule
  regula:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Regula
      uses: matte-snyk/regula-action@master
      env:
        FUGUE_API_ID: ${{ secrets.FUGUE_API_ID }}
        FUGUE_API_SECRET: ${{ secrets.FUGUE_API_SECRET }}
      with:
        sync: "true"
        environment_id: "0d63362e-dbf6-434e-8e4a-93ebf1e8b934"
